### ISSUE TITLE
New PyPI release?

### ISSUE THREAD

**Issue by msabramo** [sudarkoff/setuptools-yaml#4]
A new PyPI release would let me use Python 3.4 without getting this error:

``` pytb
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/Users/marca/dev/surveymonkey/InventorySvc/setup.py", line 6, in <module>
        pbr=True,
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/core.py", line 109, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/marca/dev/surveymonkey/InventorySvc/venv/lib/python3.4/site-packages/setuptools/dist.py", line 269, in __init__
        _Distribution.__init__(self,attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 280, in __init__
        self.finalize_options()
      File "/Users/marca/dev/surveymonkey/InventorySvc/venv/lib/python3.4/site-packages/setuptools/dist.py", line 325, in finalize_options
        ep.load()(self, ep.name, value)
      File "/Users/marca/dev/surveymonkey/InventorySvc/.eggs/setuptools_yaml-0.2-py3.4.egg/setuptools_yaml.py", line 21, in metadata_yaml
        metadata = yaml.load(file(yaml_filename, 'r'))
    NameError: name 'file' is not defined
```

**Comment by sudarkoff** [comment]
Released 0.4: https://pypi.python.org/pypi?:action=display&name=setuptools-yaml&version=0.4
